[package]
name = "ponderthis-nov"
version = "0.1.0"
edition = "2024"

[dependencies]
num-bigint = "0.4.6"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }
